Test for observing state of Replica
aartikov/Replica pull request #13
Opened 2022-02-04 10:26 UTC by EgoriusE

LoadingErrorObservingTest

ObservingTimeTest

StateObservingTest

2022-02-07 12:45 UTC, aartikov requested changes

2022-02-07 12:45 UTC, aartikov commented on replica-core/src/test/kotlin/me/aartikov/replica/single/LoadingErrorObservingTest.kt
> +    fun `inactive observer doesn't observe loading, error`() = runTest {
`doesn't observe loading, error` - давай добавим на конце слово state, чтоб обозначить что речь о ошибке как о состоянии.

2022-02-07 12:45 UTC, aartikov commented on replica-core/src/test/kotlin/me/aartikov/replica/single/LoadingErrorObservingTest.kt
> +    fun `active observer observes error`() = runTest {
observes error -> observes error event

2022-02-07 12:45 UTC, aartikov commented on replica-core/src/test/kotlin/me/aartikov/replica/single/LoadingErrorObservingTest.kt
> +    fun `active observer observes multiple errors`() = runTest {
multiple errors -> multiple error events

2022-02-07 12:45 UTC, aartikov commented on replica-core/src/test/kotlin/me/aartikov/replica/single/LoadingErrorObservingTest.kt
> +    fun `inactive observer observes multiple errors when became active`() = runTest {
Тест проверяет, что из 10 ошибок обсервер увидел только 5, поскольку вначале он был неактивен.

Тогда тест лучше назвать `observer observes error events only when active`.

2022-02-07 12:45 UTC, aartikov commented on replica-core/src/test/kotlin/me/aartikov/replica/single/LoadingErrorObservingTest.kt
> +    }
Не хватает теста `inactive observer doesn't observe error event`

2022-02-07 12:45 UTC, aartikov commented on replica-core/src/test/kotlin/me/aartikov/replica/single/LoadingErrorObservingTest.kt
> +        val errorEvents = observer.loadingErrorFlow.take(errorsCount / 2).toList()
Тут не совсем точная проверка. Если из флоу вернется 10 эвентов, то мы возьмем из них первые 5 и тест все равно пройдет.

То есть, правильнее было бы проверить, что эвентов ровно 5. И причем, это 5 последних эвентов, а не 5 первых (для этого можно сделать 10 инстансов LoadingFailedException с разными значениями).

2022-02-07 12:45 UTC, aartikov commented on replica-core/src/test/kotlin/me/aartikov/replica/single/ObservingTimeTest.kt
> +        delay(DEFAULT_DELAY)
Обязателен ли delay между observe и проверкой observingState? По-идее, состояние должно поменяться сразу, и лишние delay лучше убрать.

То же самое касается ObserverCountTest. Проверь, пожалуйста, можно ли там убрать задержки между observe и проверкой, что количество наблюдателей правильное.

2022-02-07 12:45 UTC, aartikov commented on replica-core/src/test/kotlin/me/aartikov/replica/single/ObservingTimeTest.kt
> +    fun `is never when observer observe`() = runTest {
`when observer observe` -> `when inactive observer is added`

Давай, считать, что выражение "наблюдатель наблюдает" неприменимо к неактивному наблюдателю. Неактивный наблюдатель добавлен, но пока что не наблюдает.

2022-02-07 12:45 UTC, aartikov commented on replica-core/src/test/kotlin/me/aartikov/replica/single/ObservingTimeTest.kt
> +        delay(DEFAULT_DELAY * 2)
здесь, мне кажется, можно все последовательно сделать, без дополнительного launch и без паузы перед ассертом.

Посмотри, пожалуйста, аналогичные случаи, можно ли и их исправить.

2022-02-07 12:45 UTC, aartikov commented on replica-core/src/test/kotlin/me/aartikov/replica/single/ObservingTimeTest.kt
> +    fun `is never when observer canceled`() = runTest {
`is never when observer canceled` - тут лучше уточнить все условия, потому что в общем случае утверждение неверное.

`is never when observer canceled and was not active yet`

2022-02-07 12:45 UTC, aartikov commented on replica-core/src/test/kotlin/me/aartikov/replica/single/ObservingTimeTest.kt
> +    fun `is never when observer scope canceled`() = runTest {
`... and observer was not active yet`

2022-02-07 12:45 UTC, aartikov commented on replica-core/src/test/kotlin/me/aartikov/replica/single/ObservingTimeTest.kt
> +    private val fakeTime = FakeTimeProvider().currentTime
лучше чтоб использовался тот же инстанс `FakeTimeProvider`, что был передан в реплики, иначе не совсем корректно. Можно у `replicaProvider` сделать свойство `timeProvider`.

Сам fakeTime лучше получать в методе теста, а тут оставить `private val timeProvider = replicaProvider.timeProvider`

2022-02-07 12:45 UTC, aartikov commented on replica-core/src/test/kotlin/me/aartikov/replica/single/ReplicaProvider.kt
> +}
Наверное, было бы нагляднее, если время можно было менять. То есть:

```
timeProvider.currentTime = TEST_TIME
observerActive.update { false }
...

assertEquals(ObservingTime.TimeInPast(TEST_TIME), state.observingTime)
```

TEST_TIME это константа в классе теста, ее значение лучше взять не DISTANT_PAST, а какое-то конкретное захардкоженное время.

2022-02-07 12:45 UTC, aartikov commented on replica-core/src/test/kotlin/me/aartikov/replica/single/ReplicaProvider.kt
> +        )
У ReplicaClient можно указать CoroutineScope и Dispatcher и тогда MainCoroutineRule был бы не нужен.

2022-02-07 12:45 UTC, aartikov commented on replica-core/src/test/kotlin/me/aartikov/replica/single/StateObservingTest.kt
> +        delay(DEFAULT_DELAY)
попробовать убрать delay

2022-02-07 12:45 UTC, aartikov commented on replica-core/src/test/kotlin/me/aartikov/replica/single/StateObservingTest.kt
> +        replica.refresh()
Я думаю, лучше этот тест тоже сделать через setData, а refresh и fetcher задействовать в отдельной группе тестов

2022-02-07 16:51 UTC, EgoriusE commented on replica-core/src/test/kotlin/me/aartikov/replica/single/ReplicaProvider.kt
> +        )
Пришли к выводу, что лучше использовать MainCoroutineRule

2022-02-08 09:35 UTC, aartikov approved these changes

2022-02-08 09:35 UTC, merged