Webserver output
aartikov/Replica pull request #3
Opened 2022-01-26 10:43 UTC by EgoriusE

2022-01-26 10:46 UTC, EgoriusE commented on replica-devtools-client/build.gradle
> +                directory = file("$projectDir/../replica-devtools/src/main/resources/")
Устанавливается путь, куда будут сохранены сбилденные файлы после команд `./gradlew jsBrowserProductionWebpack` или `./gradlew jsBrowserDevelopmentWebpack`

2022-01-26 11:08 UTC, aartikov requested changes

2022-01-26 11:08 UTC, aartikov commented on replica-devtools/src/main/kotlin/me/aartikov/replica/devtools/internal/WebServer.kt
> +            "ReplicaServer",
давай, сделаем тег ReplicaDevTools

2022-01-26 13:26 UTC, aartikov requested changes

2022-01-26 13:26 UTC, aartikov commented on replica-devtools-client/src/main/kotlin/me/aartikov/replica/devtools/client/main.kt
> +        Body(state)
по-моему, все кроме  Body(state) нужно вынести за пределы тела renderComposable. Потому то, что внутри renderComposable, это композабл функция, которая вызывается так часто, как ей вздумается.

2022-01-27 14:09 UTC, aartikov approved these changes

2022-01-27 14:09 UTC, merged